import { Theater, Show } from '@/types';

export interface ShowsDataResponse {
  metadata: {
    version: string;
    generatedAt: string;
    totalTheaters: number;
    totalShows: number;
    activeShows: number;
    upcomingShows: number;
    sources: string[];
  };
  theaters: Theater[];
  shows: Show[];
}

/**
 * Fetches theater and show data from the static JSON blob
 * This file is generated by the backend scraper and export process
 */
export async function fetchShowsData(): Promise<ShowsDataResponse> {
  try {
    const response = await fetch('/shows.json', {
      cache: 'no-cache', // Always get fresh data in development
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch shows data: ${response.status} ${response.statusText}`);
    }

    const data: ShowsDataResponse = await response.json();

    // Validate response structure
    if (!data.theaters || !data.shows || !data.metadata) {
      throw new Error('Invalid shows data format: missing required fields');
    }

    return data;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Error loading shows data: ${error.message}`);
    }
    throw new Error('Unknown error loading shows data');
  }
}
