import { Theater, Show } from '@/types';

export const mockTheaters: Theater[] = [
  {
    id: 't1',
    name: 'The Public Theater',
    address: '425 Lafayette St, New York, NY 10003',
    neighborhood: 'Greenwich Village',
    type: 'non-profit',
    website: 'https://publictheater.org',
    seatingCapacity: 260,
  },
  {
    id: 't2',
    name: 'Soho Playhouse',
    address: '15 Vandam St, New York, NY 10013',
    neighborhood: 'SoHo',
    type: 'off-broadway',
    website: 'https://sohoplayhouse.com',
    seatingCapacity: 178,
  },
  {
    id: 't3',
    name: 'The Tank',
    address: '312 W 36th St, New York, NY 10018',
    neighborhood: 'Midtown',
    type: 'off-off-broadway',
    website: 'https://thetanknyc.org',
    seatingCapacity: 98,
  },
  {
    id: 't4',
    name: 'La MaMa Experimental Theatre Club',
    address: '66 E 4th St, New York, NY 10003',
    neighborhood: 'East Village',
    type: 'off-off-broadway',
    website: 'https://lamama.org',
    seatingCapacity: 99,
  },
  {
    id: 't5',
    name: 'Atlantic Theater Company',
    address: '336 W 20th St, New York, NY 10011',
    neighborhood: 'Chelsea',
    type: 'off-broadway',
    website: 'https://atlantictheater.org',
    seatingCapacity: 199,
  },
];

export const mockShows: Show[] = [
  {
    id: 's1',
    title: 'The Mysteries',
    theaterId: 't1',
    description: 'A modern adaptation of medieval mystery plays exploring creation, fall, and redemption through ensemble storytelling.',
    startDate: '2025-11-20',
    endDate: '2025-12-22',
    genre: 'drama',
    runtime: 120,
    ticketPriceRange: { min: 35, max: 85 },
    website: 'https://publictheater.org/productions/the-mysteries',
  },
  {
    id: 's2',
    title: 'Comfort Food',
    theaterId: 't2',
    description: 'A hilarious comedy about a family dinner that goes hilariously wrong when unexpected guests arrive.',
    startDate: '2025-11-15',
    endDate: '2026-01-10',
    genre: 'comedy',
    runtime: 90,
    ticketPriceRange: { min: 25, max: 60 },
  },
  {
    id: 's3',
    title: 'Solo in the City',
    theaterId: 't3',
    description: 'A one-person show about navigating life, love, and loneliness in contemporary New York City.',
    startDate: '2025-11-18',
    endDate: '2025-12-01',
    genre: 'solo-show',
    runtime: 75,
    ticketPriceRange: { min: 15, max: 30 },
  },
  {
    id: 's4',
    title: 'Fragments',
    theaterId: 't4',
    description: 'An experimental dance-theatre piece exploring memory, identity, and transformation.',
    startDate: '2025-11-22',
    endDate: '2025-12-15',
    genre: 'experimental',
    runtime: 60,
    ticketPriceRange: { min: 20, max: 35 },
  },
  {
    id: 's5',
    title: 'Songs for a New World',
    theaterId: 't5',
    description: 'A song cycle musical about people at crossroads, featuring powerful ballads and ensemble numbers.',
    startDate: '2025-11-25',
    endDate: '2026-01-20',
    genre: 'musical',
    runtime: 100,
    ticketPriceRange: { min: 40, max: 95 },
    website: 'https://atlantictheater.org/songs-for-a-new-world',
  },
  {
    id: 's6',
    title: 'The Inheritance',
    theaterId: 't1',
    description: 'An epic two-part play about a generation of gay men in New York navigating love, loss, and legacy.',
    startDate: '2025-12-01',
    endDate: '2026-02-14',
    genre: 'drama',
    runtime: 210,
    ticketPriceRange: { min: 45, max: 110 },
  },
  {
    id: 's7',
    title: 'Midnight Madness',
    theaterId: 't2',
    description: 'A late-night comedy showcase featuring rotating stand-up comedians and sketch performers.',
    startDate: '2025-11-16',
    endDate: '2025-12-31',
    genre: 'comedy',
    runtime: 80,
    ticketPriceRange: { min: 20, max: 40 },
  },
];
